server:
  port: 9090
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pruebas?useSSL=false
    username: postgres
    password: admin
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
