server:
  port: 9090
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pruebas?useSSL=false
    username: postgres
    password: admin
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

##Activar en dev y qa, desactivar en prod
springdoc:
  swagger-ui: 
      enabled: true
      path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api-docs
  packages-to-scan:
  - com.mx.villalobos.biblioteca.appbiblioteca.controller
